// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOUJe-2idVlRABTlR2nsRXQCS-XuPh8Rs',
    appId: '1:327758494135:web:52f73b1262686bf9205032',
    messagingSenderId: '327758494135',
    projectId: 'fund-collection-90623',
    authDomain: 'fund-collection-90623.firebaseapp.com',
    storageBucket: 'fund-collection-90623.firebasestorage.app',
    measurementId: 'G-S333DC2BJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhIxQFE8rzOeE-zH5Tr2dbaJ_0dxU3odY',
    appId: '1:327758494135:android:083eace2e0d67dbb205032',
    messagingSenderId: '327758494135',
    projectId: 'fund-collection-90623',
    storageBucket: 'fund-collection-90623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWAxH-9fkHo7DZURObe5w8uGUJXHNUgoc',
    appId: '1:327758494135:ios:c4d68dff13961b70205032',
    messagingSenderId: '327758494135',
    projectId: 'fund-collection-90623',
    storageBucket: 'fund-collection-90623.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWAxH-9fkHo7DZURObe5w8uGUJXHNUgoc',
    appId: '1:327758494135:ios:c4d68dff13961b70205032',
    messagingSenderId: '327758494135',
    projectId: 'fund-collection-90623',
    storageBucket: 'fund-collection-90623.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOUJe-2idVlRABTlR2nsRXQCS-XuPh8Rs',
    appId: '1:327758494135:web:8f37b709a6358616205032',
    messagingSenderId: '327758494135',
    projectId: 'fund-collection-90623',
    authDomain: 'fund-collection-90623.firebaseapp.com',
    storageBucket: 'fund-collection-90623.firebasestorage.app',
    measurementId: 'G-JT1DFYSF1Q',
  );

}